### ISSUE TITLE
Explain how CHGroupPanel works

### ISSUE THREAD

**Issue by mika76** [clayreimann/CodeHelp#1]
I'm loving this addin but I see there is a plugin for a CHGroupPanel which tabs the tool windows. I cannot seem to make it work though. How do you put them in tabs?

**Comment by mika76** [comment]
Ah, I see from the code it's only the debug panes really:

```
Private Const VBA_WIN As String = "VbaWindow"
Private Const IMMED As String = "Immediate"
Private Const WATCH As String = "Watches"
Private Const LOCALS As String = "Locals"
Private Const TASK_LIST As String = "Task List"
Private Const VBPALETTE As String = "VBFloatingPalette"
```

Any way to add the Project Explorer and Properties panes as well? Maybe even the toolbox pane?

**Comment by clayreimann** [comment]
There might be, I'm not the original author of this plugin so I'm not too familiar with the code your referring to. Unfortunately, I no longer have access to VB6 or to a Windows box at all. If you figure it out feel free to submit a PR!

**Comment by mika76** [comment]
Yeah it works only on those windows - basically the panel that would show at the bottom of the VB6 IDE. I don't have time now to delve into this. Maybe in the future. I'll reopen the issue in that case...
